USE [HATO2]
GO

/****** Object:  UserDefinedFunction [dbo].[CHECK_MITSUMORI_DT]    Script Date: 07/31/2014 11:54:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/****** オブジェクト:  ユーザー定義関数 dbo.CHECK_MITSUMORI_DT    スクリプト日付: 2005/02/17 14:21:55 ******/
CREATE   FUNCTION [dbo].[CHECK_MITSUMORI_DT](@受付番号 AS CHAR(8), @組織CD AS CHAR(5), @日付FROM AS CHAR(8), @日付TO AS CHAR(8))
RETURNS CHAR(1) AS
BEGIN
DECLARE @戻り値 AS CHAR(1)
DECLARE @作業日 AS CHAR(8)
	SELECT @戻り値 = '0'
	DECLARE CUR_1 CURSOR FOR
	SELECT	ISNULL(SAGYO_DT,'') AS SAGYO_DT
	FROM	T_JUCHU_TEHAI_SYOSAI AS JTS
			INNER JOIN T_JUCHU_TEHAI AS JT
			ON	JTS.UKETSUKE_NO = JT.UKETSUKE_NO
			AND	JTS.SOSHIKI_CD = JT.SOSHIKI_CD
			AND	JTS.TEHAI_SEQ = JT.TEHAI_SEQ
	WHERE	JT.DELETE_FLG = '0'
		AND	JTS.DELETE_FLG = '0'
		AND	JT.TEHAI_SHUBETSU_CD = '01'
		AND	JTS.UKETSUKE_NO = @受付番号
		AND	JTS.SOSHIKI_CD	= @組織CD
	OPEN CUR_1
	FETCH  NEXT FROM CUR_1 INTO @作業日
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF @作業日 <> '' AND @作業日 >= @日付FROM AND @作業日 <= @日付TO
			SELECT @戻り値 = '1' 
		FETCH  NEXT FROM CUR_1 INTO @作業日
	END
	CLOSE CUR_1
	DEALLOCATE CUR_1
	RETURN @戻り値
END


GO

