USE [HATO2]
GO

/****** Object:  UserDefinedFunction [dbo].[GET_JUSHO_CD]    Script Date: 07/31/2014 11:57:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[GET_JUSHO_CD] (@JUSHO_IN AS VARCHAR(30))  
RETURNS CHAR(5) AS  
BEGIN
DECLARE
	@JUSHO_CD		CHAR(5),
	@JUSHO		VARCHAR(31)
	--前方検索する
	SET @JUSHO = '%' + RTRIM(@JUSHO_IN)
	SET @JUSHO_CD = NULL
	--住所コードを取得
	DECLARE CUR_JUSHO CURSOR FOR
		SELECT TOP 1 SHIKUGUN_CD
		FROM	M_YUBIN_BANGO
		WHERE	ADDRESS_KANJI1 LIKE @JUSHO
		ORDER BY SHIKUGUN_CD
	OPEN CUR_JUSHO
	FETCH FROM CUR_JUSHO INTO @JUSHO_CD
	CLOSE CUR_JUSHO
	DEALLOCATE CUR_JUSHO
	RETURN @JUSHO_CD
END

GO

