USE [HATO2]
GO

/****** Object:  UserDefinedFunction [dbo].[CAN_USE_DELETE_BTN]    Script Date: 07/31/2014 11:54:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [dbo].[CAN_USE_DELETE_BTN] (@IN_UKETSUKE_NO AS CHAR(8),@IN_GYOMU_SEQ CHAR(2))  
RETURNS INT AS  
BEGIN
	DECLARE
		@GYOMU_SEQ CHAR(2),
		@RET		INT

	--入力業務ＳＥＱ以上の業務ＳＥＱを取得
	DECLARE CUR_GYOMU CURSOR FOR
		SELECT GYOMU_SEQ
		FROM	T_JUCHU_GYOMU
		WHERE UKETSUKE_NO  = @IN_UKETSUKE_NO
		AND   CONVERT(DECIMAL(2),GYOMU_SEQ) >= CONVERT(DECIMAL(2),@IN_GYOMU_SEQ)
		AND   DELETE_FLG   = 0
		ORDER BY CONVERT(DECIMAL(2),GYOMU_SEQ)

	SET @RET = 0

	OPEN CUR_GYOMU
	FETCH NEXT FROM CUR_GYOMU INTO
		@GYOMU_SEQ
	WHILE (@@FETCH_STATUS = 0)
	BEGIN

		--一件でも業務区分変更不可の業務ＳＥＱが存在した場合は処理を抜ける
		SELECT @RET = dbo.CAN_CHANGE_GYOMU_KBN(@IN_UKETSUKE_NO,@GYOMU_SEQ)
		IF @RET = 0
			GOTO EXIT_LOOP;

		FETCH  NEXT FROM CUR_GYOMU INTO
			@GYOMU_SEQ
	END

EXIT_LOOP:
	CLOSE CUR_GYOMU
	DEALLOCATE CUR_GYOMU

	RETURN @RET

END


GO

