USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_COM_DELETE_KENSAKU_CONDITION]    Script Date: 07/31/2014 11:43:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_COM_DELETE_KENSAKU_CONDITION]
AS
DECLARE
	@ERR INT,
	@PRC_DATE DATETIME
BEGIN

	--システム日の00:00:00を取得
	SET @PRC_DATE = CONVERT(DATETIME,CONVERT(CHAR(8),GETDATE(),112),112)

	SET @ERR = 0

	--検索結果データを削除する
	DELETE W_COM_KENSAKU_RES
		WHERE CREATE_DT < @PRC_DATE
	IF @@ERROR != 0
	BEGIN
		SET @ERR = @@ERROR
		GOTO SP_COM_DELETE_KENSAKU_CONDITION
	END

	DELETE W_COM_KENSAKU_CND
		WHERE CREATE_DT < @PRC_DATE
	IF @@ERROR != 0
	BEGIN
		SET @ERR = @@ERROR
	END

	DELETE W_EXPORT_CSV
		WHERE CREATE_DT < @PRC_DATE
	IF @@ERROR != 0
	BEGIN
		SET @ERR = @@ERROR
	END

SP_COM_DELETE_KENSAKU_CONDITION:
	RETURN @ERR

END

GO

