USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_DF0400]    Script Date: 07/31/2014 11:44:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_DF0400](
    @SESSION_CD     AS CHAR(30),
	@NENGETSU_IN 	AS CHAR(7),
	@SOSHIKI_CD_IN	AS CHAR(5),
	@CT_OUT			AS INT OUTPUT
)
AS
DECLARE
	@W_NENGETSU 	            AS VARCHAR(8),
	@W_SOSHIKI_CD	            AS VARCHAR(6),

	@m_J_AREA_CD				AS CHAR(8),
	@m_AREA_CD					AS CHAR(8),
	@m_SOSHIKI_CD				AS CHAR(5),
	@m_SOSHIKI_RYAKU_MEI		AS VARCHAR(20),
	@m_KENSU_1					AS NUMERIC(9),
	@m_RYOKIN_KEI_1				AS DECIMAL(10,0),
	@m_KENSU_2					AS NUMERIC(9),
	@m_RYOKIN_KEI_2				AS DECIMAL(10,0),
	@m_KENSU_3					AS NUMERIC(9),
	@m_RYOKIN_KEI_3				AS DECIMAL(10,0),
	@m_KENSU_4					AS NUMERIC(9),
	@m_RYOKIN_KEI_4				AS DECIMAL(10,0),
	@m_KENSU_5					AS NUMERIC(9),
	@m_RYOKIN_KEI_5				AS DECIMAL(10,0),
	@m_KOKYAKU_KANRI_RIRITU		AS DECIMAL(7,5),

	@m_KOKYAKU_KEI				AS DECIMAL(10,0),

	@m_B_KENSU_1				AS NUMERIC(9),
	@m_B_RYOKIN_KEI_1			AS DECIMAL(10,0),
	@m_B_KENSU_2				AS NUMERIC(9),
	@m_B_RYOKIN_KEI_2			AS DECIMAL(10,0),
	@m_B_KENSU_3				AS NUMERIC(9),
	@m_B_RYOKIN_KEI_3			AS DECIMAL(10,0),
	@m_B_KENSU_4				AS NUMERIC(9),
	@m_B_RYOKIN_KEI_4			AS DECIMAL(10,0),
	@m_B_KENSU_5				AS NUMERIC(9),
	@m_B_RYOKIN_KEI_5			AS DECIMAL(10,0),
	@m_B_KOKYAKU_KEI			AS DECIMAL(10,0),

	@m_T_KENSU_1				AS NUMERIC(9),
	@m_T_RYOKIN_KEI_1			AS DECIMAL(10,0),
	@m_T_KENSU_2				AS NUMERIC(9),
	@m_T_RYOKIN_KEI_2			AS DECIMAL(10,0),
	@m_T_KENSU_3				AS NUMERIC(9),
	@m_T_RYOKIN_KEI_3			AS DECIMAL(10,0),
	@m_T_KENSU_4				AS NUMERIC(9),
	@m_T_RYOKIN_KEI_4			AS DECIMAL(10,0),
	@m_T_KENSU_5				AS NUMERIC(9),
	@m_T_RYOKIN_KEI_5			AS DECIMAL(10,0),
	@m_T_KOKYAKU_KEI			AS DECIMAL(10,0),

    @m_EXPDT                    AS CHAR(6),
    @m_IDX                      AS INT,
    @m_IDX2                     AS INT,
    @m_START                    AS INT,
	@m_TITLE					AS VARCHAR(20),
	@m_OLD_J_AREA_CD			AS CHAR(8),
	@m_OLD_AREA_CD				AS CHAR(8),
	@m_BUF                      AS VARCHAR(1024)

BEGIN
	SET @CT_OUT =0

    SET @m_EXPDT = CASE LEN(REPLACE(@NENGETSU_IN,'/','')) 
                            WHEN 4 THEN '20' + REPLACE(@NENGETSU_IN,'/','')
                            WHEN 6 THEN REPLACE(@NENGETSU_IN,'/','') END

    SET @W_NENGETSU = RTRIM(@m_EXPDT) + '%'
    SET @W_SOSHIKI_CD = RTRIM(@SOSHIKI_CD_IN)
	SET @m_TITLE = '顧客管理収入一覧表'

    --ワークテーブルに書き込み
    INSERT INTO W_DF0400 (
        SESSION_CD,
		J_AREA_CD,
		AREA_CD,
		SOSHIKI_CD,
		SOSHIKI_RYAKU_MEI,
		KENSU_1,
		RYOKIN_KEI_1,
		KENSU_2,
		RYOKIN_KEI_2,
		KENSU_3,
		RYOKIN_KEI_3,
		KENSU_4,
		RYOKIN_KEI_4,
		KENSU_5,
		RYOKIN_KEI_5,
		KOKYAKU_KANRI_RIRITU
	)
    SELECT @SESSION_CD,
		REPLACE(MS1.AREA_CD, ' ', 'XXXXXXXX'), 
		REPLACE(ISNULL(MA.AREA_CD,' '), ' ', 'XXXXXXXX'), 
		MS.SOSHIKI_CD,
		MS.SOSHIKI_RYAKU_MEI,
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '1' THEN 1 
			WHEN '2' THEN 1 
			ELSE 0 
		END * ISNULL(JH.JISSEKI_KEN_SU,0),
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '1' THEN 1
			WHEN '2' THEN 1
            ELSE 0 
		--END * (ISNULL(JR.RYOKIN_KEI, 0) - ISNULL(JR.SHOHIZEI_GK, 0) - ISNULL(JR.RYOKIN_NEBIKI_GKS, 0)),
		END * (ISNULL(JR.RYOKIN_1,0) + ISNULL(JR.RYOKIN_2,0) + ISNULL(JR.RYOKIN_3,0) + 
				ISNULL(JR.RYOKIN_4,0) + ISNULL(JR.RYOKIN_5,0) + ISNULL(JR.RYOKIN_6,0) - ISNULL(JR.KOJINFUTAN_GK,0) + 
				ISNULL(JR.RYOKIN_NEBIKI_GK1,0) + ISNULL(JR.RYOKIN_NEBIKI_GKN,0)),
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '3' THEN 1 
			ELSE 0 
		END * ISNULL(JH.JISSEKI_KEN_SU,0),
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '3' THEN 1
			ELSE 0 
		--END * (ISNULL(JR.RYOKIN_KEI, 0) - ISNULL(JR.SHOHIZEI_GK, 0) - ISNULL(JR.RYOKIN_NEBIKI_GKS, 0)),
		END * (ISNULL(JR.RYOKIN_1,0) + ISNULL(JR.RYOKIN_2,0) + ISNULL(JR.RYOKIN_3,0) + 
				ISNULL(JR.RYOKIN_4,0) + ISNULL(JR.RYOKIN_5,0) + ISNULL(JR.RYOKIN_6,0) - ISNULL(JR.KOJINFUTAN_GK,0) + 
				ISNULL(JR.RYOKIN_NEBIKI_GK1,0) + ISNULL(JR.RYOKIN_NEBIKI_GKN,0)),
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '1' THEN 1 
			WHEN '2' THEN 1 
			WHEN '3' THEN 1 
			ELSE 0 
		END * ISNULL(JH.JISSEKI_KEN_SU,0),
		CASE LEFT(JS.JISSEKI_KEIJO_KBN, 1) 
			WHEN '1' THEN 1 
			WHEN '2' THEN 1 
			WHEN '3' THEN 1 
			ELSE 0 
		--END * (ISNULL(JR.RYOKIN_KEI, 0) - ISNULL(JR.SHOHIZEI_GK, 0) - ISNULL(JR.RYOKIN_NEBIKI_GKS, 0)),
		END * (ISNULL(JR.RYOKIN_1,0) + ISNULL(JR.RYOKIN_2,0) + ISNULL(JR.RYOKIN_3,0) + 
				ISNULL(JR.RYOKIN_4,0) + ISNULL(JR.RYOKIN_5,0) + ISNULL(JR.RYOKIN_6,0) - ISNULL(JR.KOJINFUTAN_GK,0) + 
				ISNULL(JR.RYOKIN_NEBIKI_GK1,0) + ISNULL(JR.RYOKIN_NEBIKI_GKN,0)),
		CASE JS.HOKEN_TAISHO_FLG 
			WHEN '1' THEN 1 
			ELSE 0 
		END * ISNULL(JH.JISSEKI_KEN_SU,0),
		CASE JS.HOKEN_TAISHO_FLG 
			WHEN '1' THEN 1 
			ELSE 0 
		--END * (ISNULL(JR.RYOKIN_KEI, 0) - ISNULL(JR.SHOHIZEI_GK, 0) - ISNULL(JR.RYOKIN_NEBIKI_GKS, 0)),
		END * (ISNULL(JR.RYOKIN_1,0) + ISNULL(JR.RYOKIN_2,0) + ISNULL(JR.RYOKIN_3,0) + 
				ISNULL(JR.RYOKIN_4,0) + ISNULL(JR.RYOKIN_5,0) + ISNULL(JR.RYOKIN_6,0) - ISNULL(JR.KOJINFUTAN_GK,0) + 
				ISNULL(JR.RYOKIN_NEBIKI_GK1,0) + ISNULL(JR.RYOKIN_NEBIKI_GKN,0)),
		CASE JS.HOKEN_TAISHO_FLG 
			WHEN '0' THEN 1 
			ELSE 0 
		END * ISNULL(JH.JISSEKI_KEN_SU,0),
		CASE JS.HOKEN_TAISHO_FLG 
			WHEN '0' THEN 1 
			ELSE 0 
		--END * (ISNULL(JR.RYOKIN_KEI, 0) - ISNULL(JR.SHOHIZEI_GK, 0) - ISNULL(JR.RYOKIN_NEBIKI_GKS, 0)),
		END * (ISNULL(JR.RYOKIN_1,0) + ISNULL(JR.RYOKIN_2,0) + ISNULL(JR.RYOKIN_3,0) + 
				ISNULL(JR.RYOKIN_4,0) + ISNULL(JR.RYOKIN_5,0) + ISNULL(JR.RYOKIN_6,0) - ISNULL(JR.KOJINFUTAN_GK,0) + 
				ISNULL(JR.RYOKIN_NEBIKI_GK1,0) + ISNULL(JR.RYOKIN_NEBIKI_GKN,0)),
		MS.KOKYAKU_KANRI_RIRITU
	FROM M_SOSHIKI MS
		LEFT JOIN M_SOSHIKI MS1
			ON  MS1.SOSHIKI_CD = MS.JYOBU_SOSHIKI_CD
			AND MS1.DELETE_FLG = '0'
		LEFT JOIN M_AREA MA
			ON  MA.AREA_CD = MS.AREA_CD
			AND MA.DELETE_FLG = '0'
		LEFT JOIN T_JUCHU_SYOSAI JS
			INNER JOIN T_JUCHU_KIHON JK
				LEFT JOIN T_JUCHU_HOJO JH
					ON JH.UKETSUKE_NO = JK.UKETSUKE_NO
					AND JH.DELETE_FLG = '0'
				ON 	JK.UKETSUKE_NO = JS.UKETSUKE_NO
				AND JK.DELETE_FLG = '0'
				AND JK.JUCHU_STS_CD ='05'
				AND JK.JISSEKI_DT LIKE @W_NENGETSU
			LEFT JOIN T_JUCHU_RYOKIN JR
				ON  JR.UKETSUKE_NO = JS.UKETSUKE_NO
				AND JR.SOSHIKI_CD = JS.SOSHIKI_CD
				AND JR.DELETE_FLG = '0'
			ON  JS.SOSHIKI_CD = MS.SOSHIKI_CD
			AND JS.DELETE_FLG = '0'
			AND JS.JISSEKI_KBN = '1'
			AND LEFT(JS.JISSEKI_KEIJO_KBN, 1) IN ('1','2','3')

	WHERE MS.SOSHIKI_KBN = '3'
	AND MS.DELETE_FLG = '0'
	AND (MS1.JYOBU_SOSHIKI_CD = @W_SOSHIKI_CD 
		OR MS.JYOBU_SOSHIKI_CD = @W_SOSHIKI_CD
		OR MS.SOSHIKI_CD = @W_SOSHIKI_CD )

    SET @m_OLD_AREA_CD = ''

    SET @m_B_KENSU_1 = 0      
    SET @m_B_RYOKIN_KEI_1 = 0          
    SET @m_B_KENSU_2 = 0      
    SET @m_B_RYOKIN_KEI_2 = 0          
    SET @m_B_KENSU_3 = 0      
    SET @m_B_RYOKIN_KEI_3 = 0          
    SET @m_B_KENSU_4 = 0      
    SET @m_B_RYOKIN_KEI_4 = 0          
    SET @m_B_KENSU_5 = 0      
    SET @m_B_RYOKIN_KEI_5 = 0          
    SET @m_B_KOKYAKU_KEI = 0      

    SET @m_T_KENSU_1 = 0      
    SET @m_T_RYOKIN_KEI_1 = 0          
    SET @m_T_KENSU_2 = 0      
    SET @m_T_RYOKIN_KEI_2 = 0          
    SET @m_T_KENSU_3 = 0      
    SET @m_T_RYOKIN_KEI_3 = 0          
    SET @m_T_KENSU_4 = 0      
    SET @m_T_RYOKIN_KEI_4 = 0          
    SET @m_T_KENSU_5 = 0      
    SET @m_T_RYOKIN_KEI_5 = 0          
    SET @m_T_KOKYAKU_KEI = 0      

    SET @m_IDX = 0
    SET @m_IDX2 = 1
    SET @m_START = 1

    --計算してＣＳＶデータ作成
    DECLARE c_W_DF0400 CURSOR FOR
		SELECT 
			J_AREA_CD,
			AREA_CD,
			SOSHIKI_CD,
			SOSHIKI_RYAKU_MEI,
			SUM(KENSU_1),
			SUM(RYOKIN_KEI_1),
			SUM(KENSU_2),
			SUM(RYOKIN_KEI_2),
			SUM(KENSU_3),
			SUM(RYOKIN_KEI_3),
			SUM(KENSU_4),
			SUM(RYOKIN_KEI_4),
			SUM(KENSU_5),
			SUM(RYOKIN_KEI_5),
			KOKYAKU_KANRI_RIRITU
		FROM W_DF0400
		WHERE SESSION_CD = @SESSION_CD
		GROUP BY
			J_AREA_CD,
			AREA_CD,
			SOSHIKI_CD,
			SOSHIKI_RYAKU_MEI,
			KOKYAKU_KANRI_RIRITU
		ORDER BY J_AREA_CD, AREA_CD, SOSHIKI_CD
    OPEN c_W_DF0400
    FETCH NEXT FROM c_W_DF0400 INTO 
		@m_J_AREA_CD,
		@m_AREA_CD,
		@m_SOSHIKI_CD,
		@m_SOSHIKI_RYAKU_MEI,
		@m_KENSU_1,
		@m_RYOKIN_KEI_1,
		@m_KENSU_2,
		@m_RYOKIN_KEI_2,
		@m_KENSU_3,
		@m_RYOKIN_KEI_3,
		@m_KENSU_4,
		@m_RYOKIN_KEI_4,
		@m_KENSU_5,
		@m_RYOKIN_KEI_5,
		@m_KOKYAKU_KANRI_RIRITU

	    WHILE @@FETCH_STATUS = 0
	    BEGIN
            SET @m_IDX = @m_IDX + 1

        --見出し行のINSERT
	    IF @m_START =1
	    BEGIN
	        SET @m_START = 0
            SET @m_BUF = '[' + LEFT(@m_EXPDT,4) + '年' + SUBSTRING(@m_EXPDT,5,2) + '月度　' + @m_TITLE + '],,,,,,,,,,,,,'
            INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
            SET @m_IDX2 = @m_IDX2 + 1
			SET @m_BUF = ''
            INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
            SET @m_IDX2 = @m_IDX2 + 1
            SET @m_BUF = 'コード,センター名,引越,,生活関連,,合計,,保険対象,,保険対象外,,利率,顧客管理収入'
            INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
            SET @m_IDX2 = @m_IDX2 + 1
            SET @m_BUF = ',,件数,金額,件数,金額,件数,金額,件数,金額,件数,金額,,金額'
            INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
            SET @m_IDX2 = @m_IDX2 + 1
            SET @m_OLD_J_AREA_CD = @m_J_AREA_CD
            SET @m_OLD_AREA_CD = @m_AREA_CD
        END
        ELSE
        BEGIN
            IF @m_J_AREA_CD <> @m_OLD_J_AREA_CD OR @m_AREA_CD <> @m_OLD_AREA_CD 
            BEGIN
                SET @m_BUF ='小計,,' 
						+ CONVERT(VARCHAR, @m_B_KENSU_1) + ','
						+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_1) + ','
						+ CONVERT(VARCHAR, @m_B_KENSU_2) + ','
						+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_2) + ','
						+ CONVERT(VARCHAR, @m_B_KENSU_3) + ','
						+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_3) + ','
						+ CONVERT(VARCHAR, @m_B_KENSU_4) + ','
						+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_4) + ','
						+ CONVERT(VARCHAR, @m_B_KENSU_5) + ','
						+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_5) + ',,'
						+ CONVERT(VARCHAR, @m_B_KOKYAKU_KEI)
                INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
                SET @m_IDX2 = @m_IDX2 + 1

	            SET @m_OLD_J_AREA_CD = @m_J_AREA_CD
	            SET @m_OLD_AREA_CD = @m_AREA_CD

                SET @m_B_KENSU_1 = 0      
                SET @m_B_RYOKIN_KEI_1 = 0          
                SET @m_B_KENSU_2 = 0      
                SET @m_B_RYOKIN_KEI_2 = 0          
                SET @m_B_KENSU_3 = 0      
                SET @m_B_RYOKIN_KEI_3 = 0          
                SET @m_B_KENSU_4 = 0      
                SET @m_B_RYOKIN_KEI_4 = 0          
                SET @m_B_KENSU_5 = 0      
                SET @m_B_RYOKIN_KEI_5 = 0          
                SET @m_B_KOKYAKU_KEI = 0      
            END
	    END

		--顧客管理収入金額の計算
		SET @m_KOKYAKU_KEI = @m_RYOKIN_KEI_4 * @m_KOKYAKU_KANRI_RIRITU

		--小計の計算
		SET @m_B_KENSU_1 = @m_B_KENSU_1 + @m_KENSU_1
		SET @m_B_RYOKIN_KEI_1 = @m_B_RYOKIN_KEI_1 + @m_RYOKIN_KEI_1
		SET @m_B_KENSU_2 = @m_B_KENSU_2 + @m_KENSU_2
		SET @m_B_RYOKIN_KEI_2 = @m_B_RYOKIN_KEI_2 + @m_RYOKIN_KEI_2
		SET @m_B_KENSU_3 = @m_B_KENSU_3 + @m_KENSU_3
		SET @m_B_RYOKIN_KEI_3 = @m_B_RYOKIN_KEI_3 + @m_RYOKIN_KEI_3
		SET @m_B_KENSU_4 = @m_B_KENSU_4 + @m_KENSU_4
		SET @m_B_RYOKIN_KEI_4 = @m_B_RYOKIN_KEI_4 + @m_RYOKIN_KEI_4
		SET @m_B_KENSU_5 = @m_B_KENSU_5 + @m_KENSU_5
		SET @m_B_RYOKIN_KEI_5 = @m_B_RYOKIN_KEI_5 + @m_RYOKIN_KEI_5
		SET @m_B_KOKYAKU_KEI = @m_B_KOKYAKU_KEI + @m_KOKYAKU_KEI

		--合計の計算
		SET @m_T_KENSU_1 = @m_T_KENSU_1 + @m_KENSU_1
		SET @m_T_RYOKIN_KEI_1 = @m_T_RYOKIN_KEI_1 + @m_RYOKIN_KEI_1
		SET @m_T_KENSU_2 = @m_T_KENSU_2 + @m_KENSU_2
		SET @m_T_RYOKIN_KEI_2 = @m_T_RYOKIN_KEI_2 + @m_RYOKIN_KEI_2
		SET @m_T_KENSU_3 = @m_T_KENSU_3 + @m_KENSU_3
		SET @m_T_RYOKIN_KEI_3 = @m_T_RYOKIN_KEI_3 + @m_RYOKIN_KEI_3
		SET @m_T_KENSU_4 = @m_T_KENSU_4 + @m_KENSU_4
		SET @m_T_RYOKIN_KEI_4 = @m_T_RYOKIN_KEI_4 + @m_RYOKIN_KEI_4
		SET @m_T_KENSU_5 = @m_T_KENSU_5 + @m_KENSU_5
		SET @m_T_RYOKIN_KEI_5 = @m_T_RYOKIN_KEI_5 + @m_RYOKIN_KEI_5
		SET @m_T_KOKYAKU_KEI = @m_T_KOKYAKU_KEI + @m_KOKYAKU_KEI

        --明細行出力
        SET @m_BUF = @m_SOSHIKI_CD + ',' 
                   + @m_SOSHIKI_RYAKU_MEI + ',' 
				   + CONVERT(VARCHAR, @m_KENSU_1) + ','
				   + CONVERT(VARCHAR, @m_RYOKIN_KEI_1) + ','
				   + CONVERT(VARCHAR, @m_KENSU_2) + ','
				   + CONVERT(VARCHAR, @m_RYOKIN_KEI_2) + ','
				   + CONVERT(VARCHAR, @m_KENSU_3) + ','
				   + CONVERT(VARCHAR, @m_RYOKIN_KEI_3) + ','
				   + CONVERT(VARCHAR, @m_KENSU_4) + ','
				   + CONVERT(VARCHAR, @m_RYOKIN_KEI_4) + ','
				   + CONVERT(VARCHAR, @m_KENSU_5) + ','
				   + CONVERT(VARCHAR, @m_RYOKIN_KEI_5) + ','
				   + CONVERT(VARCHAR, @m_KOKYAKU_KANRI_RIRITU) + ','
				   + CONVERT(VARCHAR, @m_KOKYAKU_KEI)
        INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
        SET @m_IDX2 = @m_IDX2 + 1

	    FETCH NEXT FROM c_W_DF0400 INTO 
			@m_J_AREA_CD,
			@m_AREA_CD,
			@m_SOSHIKI_CD,
			@m_SOSHIKI_RYAKU_MEI,
			@m_KENSU_1,
			@m_RYOKIN_KEI_1,
			@m_KENSU_2,
			@m_RYOKIN_KEI_2,
			@m_KENSU_3,
			@m_RYOKIN_KEI_3,
			@m_KENSU_4,
			@m_RYOKIN_KEI_4,
			@m_KENSU_5,
			@m_RYOKIN_KEI_5,
			@m_KOKYAKU_KANRI_RIRITU
	END

    SET @m_BUF ='小計,,' 
			+ CONVERT(VARCHAR, @m_B_KENSU_1) + ','
			+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_1) + ','
			+ CONVERT(VARCHAR, @m_B_KENSU_2) + ','
			+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_2) + ','
			+ CONVERT(VARCHAR, @m_B_KENSU_3) + ','
			+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_3) + ','
			+ CONVERT(VARCHAR, @m_B_KENSU_4) + ','
			+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_4) + ','
			+ CONVERT(VARCHAR, @m_B_KENSU_5) + ','
			+ CONVERT(VARCHAR, @m_B_RYOKIN_KEI_5) + ',,'
			+ CONVERT(VARCHAR, @m_B_KOKYAKU_KEI)
    INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    
    SET @m_IDX2 = @m_IDX2 + 1

    SET @m_BUF ='合計,,' 
			+ CONVERT(VARCHAR, @m_T_KENSU_1) + ','
			+ CONVERT(VARCHAR, @m_T_RYOKIN_KEI_1) + ','
			+ CONVERT(VARCHAR, @m_T_KENSU_2) + ','
			+ CONVERT(VARCHAR, @m_T_RYOKIN_KEI_2) + ','
			+ CONVERT(VARCHAR, @m_T_KENSU_3) + ','
			+ CONVERT(VARCHAR, @m_T_RYOKIN_KEI_3) + ','
			+ CONVERT(VARCHAR, @m_T_KENSU_4) + ','
			+ CONVERT(VARCHAR, @m_T_RYOKIN_KEI_4) + ','
			+ CONVERT(VARCHAR, @m_T_KENSU_5) + ','
			+ CONVERT(VARCHAR, @m_T_RYOKIN_KEI_5) + ',,'
			+ CONVERT(VARCHAR, @m_T_KOKYAKU_KEI)
    INSERT INTO W_EXPORT_CSV(SESSION_CD,LINE_NO,LINE_BUFFER) VALUES(@SESSION_CD,@m_IDX2,@m_BUF)    

    CLOSE c_W_DF0400
    DEALLOCATE c_W_DF0400

	--ワークの削除
	DELETE W_DF0400 WHERE SESSION_CD = @SESSION_CD 

    SET @CT_OUT = @m_IDX
END


GO

