USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_KYUKAKYUSYA_KENSAKU_OTHER]    Script Date: 07/31/2014 11:49:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_KYUKAKYUSYA_KENSAKU_OTHER](
	@IN_SESSION_ID         AS CHAR(30),
	@IN_SOSHIKI_CD         AS CHAR(5),
	@IN_KYUKAKYUSYA_KBN    AS CHAR(1),
	@IN_SAGYO_DATE_F       AS CHAR(8),
	@IN_SAGYO_DATE_T       AS CHAR(8),
	@IN_HATSU_AREA_CD      AS CHAR(2),
	@IN_HATSU_TODOFUKEN_CD AS CHAR(2),
	@IN_CHAKU_AREA_CD      AS CHAR(2),
	@IN_CHAKU_TODOFUKEN_CD AS CHAR(2),
	@IN_HATSU_SOSHIKI_CD   AS CHAR(5),
	@IN_SEIYAKU_KBN_OP     AS CHAR(4),
	@IN_KYOSO_KBN		   AS CHAR(3)
)
AS
DECLARE
	@ERR                   INT,
	@C_KYUKAKYUSYA_KBN     CHAR(1),
	@C_SAGYO_DATE_F        CHAR(8),
	@C_SAGYO_DATE_T        CHAR(8),
	@C_HATSU_AREA_CD       CHAR(2),
	@C_HATSU_TODOFUKEN_CD  CHAR(2),
	@C_CHAKU_AREA_CD       CHAR(2),
	@C_CHAKU_TODOFUKEN_CD  CHAR(2),
	@C_HATSU_SOSHIKI_CD    CHAR(5),
	@C_SEIYAKU_KBN_OP      CHAR(4),
	@C_KYOSO_KBN		   CHAR(3)
	
BEGIN

	SET @ERR = 0

	SET @C_KYUKAKYUSYA_KBN    = ''+RTRIM(@IN_KYUKAKYUSYA_KBN)
	SET @C_SAGYO_DATE_F       = ''+RTRIM(@IN_SAGYO_DATE_F)
	SET @C_SAGYO_DATE_T       = ''+RTRIM(@IN_SAGYO_DATE_T)
	SET @C_HATSU_AREA_CD      = ''+RTRIM(@IN_HATSU_AREA_CD)
	SET @C_HATSU_TODOFUKEN_CD = ''+RTRIM(@IN_HATSU_TODOFUKEN_CD)
	SET @C_CHAKU_AREA_CD      = ''+RTRIM(@IN_CHAKU_AREA_CD)
	SET @C_CHAKU_TODOFUKEN_CD = ''+RTRIM(@IN_CHAKU_TODOFUKEN_CD)
	SET @C_HATSU_SOSHIKI_CD   = ''+RTRIM(@IN_HATSU_SOSHIKI_CD)
	SET @C_SEIYAKU_KBN_OP     = ''+RTRIM(@IN_SEIYAKU_KBN_OP)
	-- ========== Str 2010/10/22 Ins SYS_Ohki ==========
	SET @C_KYOSO_KBN          = ''+RTRIM(@IN_KYOSO_KBN)
	-- ========== End 2010/10/22 Ins SYS_Ohki ==========


	--成約状況で「全て」を選択されている場合
	IF SUBSTRING(@C_SEIYAKU_KBN_OP,1,1) = '1'
		SET @C_SEIYAKU_KBN_OP = '1111'
	
	-- ========== Str 2010/10/22 Ins SYS_Ohki ==========
	IF SUBSTRING(@C_KYOSO_KBN,1,1) = '1' 
		SET @C_KYOSO_KBN = '111'
	-- ========== End 2010/10/22 Ins SYS_Ohki ==========
/*
	--全ての条件が指定されていない場合は、発日をシステム日付以降で抽出を行う。
	IF  (@C_KYUKAKYUSYA_KBN ='0')
	AND (RTRIM(@C_SAGYO_DATE_F)  = ''  AND RTRIM(@C_SAGYO_DATE_T)  = '')
	AND (@C_HATSU_TODOFUKEN_CD  = '00' AND @C_HATSU_AREA_CD  = '00')
	AND (@C_CHAKU_TODOFUKEN_CD  = '00' AND @C_CHAKU_AREA_CD  = '00')
	AND (RTRIM(@C_HATSU_SOSHIKI_CD) = '')
		SET @C_SAGYO_DATE_F = CONVERT(CHAR(8),GETDATE(),112)
*/
	--検索結果データを削除する
	DELETE W_COM_KENSAKU_RES
		WHERE SESSION_CD = @IN_SESSION_ID

	INSERT INTO W_COM_KENSAKU_RES(
				SESSION_CD,
				UKETSUKE_NO,
				SOSHIKI_CD
				)
		SELECT	TOP 301
				@IN_SESSION_ID,
				KK.KYUKAKYUSYA_NO,
				@IN_SOSHIKI_CD
			FROM
				T_KYUKAKYUSYA AS KK
				LEFT JOIN T_KYUKAKYUSYA_M AS KMT
				ON (KMT.KYUKAKYUSYA_NO = KK.KYUKAKYUSYA_NO
				AND KMT.SAGYO_KBN = '1')
				LEFT JOIN T_KYUKAKYUSYA_M AS KMO
				ON (KMO.KYUKAKYUSYA_NO = KK.KYUKAKYUSYA_NO
				AND KMO.SAGYO_KBN = '2')
				--------------------------------------------------------
				-- 2010/10/22 Ins SYS_Ohki
				LEFT JOIN M_SOSHIKI HASSIN
				ON   KK.HASSIN_CENTER_CD = HASSIN.SOSHIKI_CD
				AND  HASSIN.DELETE_FLG   = '0'
				LEFT JOIN M_SOSHIKI SESSION
				ON   @IN_SOSHIKI_CD      = SESSION.SOSHIKI_CD
				AND  SESSION.DELETE_FLG  = '0'
				--------------------------------------------------------
			WHERE KK.DELETE_FLG  = '0'
			AND	(--求貨求車区分
					(@C_KYUKAKYUSYA_KBN ='0')
				OR	(KK.KYUKAKYUSYA_KBN = @C_KYUKAKYUSYA_KBN)
				)
			AND	(--発日
					(RTRIM(@C_SAGYO_DATE_F)  = '' AND RTRIM(@C_SAGYO_DATE_T)  = '')
				OR	(RTRIM(@C_SAGYO_DATE_F) != '' AND RTRIM(@C_SAGYO_DATE_T) != ''
					AND KMT.SAGYO_DT_FROM    BETWEEN @C_SAGYO_DATE_F AND @C_SAGYO_DATE_T)
				OR	(RTRIM(@C_SAGYO_DATE_F) != '' AND RTRIM(@C_SAGYO_DATE_T)  = ''
					AND KMT.SAGYO_DT_FROM   >= @C_SAGYO_DATE_F)
				OR	(RTRIM(@C_SAGYO_DATE_F)  = '' AND RTRIM(@C_SAGYO_DATE_T) != ''
					AND KMT.SAGYO_DT_FROM   <= @C_SAGYO_DATE_T)
				)
			AND	(--発地
					(@C_HATSU_TODOFUKEN_CD  = '00' AND @C_HATSU_AREA_CD  = '00')
				OR	(@C_HATSU_TODOFUKEN_CD != '00' AND KMT.TODOFUKEN_CD  = @C_HATSU_TODOFUKEN_CD)
				OR	(@C_HATSU_TODOFUKEN_CD  = '00' AND @C_HATSU_AREA_CD != '00' AND KMT.AREA_CD  = @C_HATSU_AREA_CD)
				)
			AND	(--着地
					(@C_CHAKU_TODOFUKEN_CD  = '00' AND @C_CHAKU_AREA_CD  = '00')
				OR	(@C_CHAKU_TODOFUKEN_CD != '00' AND KMO.TODOFUKEN_CD  = @C_CHAKU_TODOFUKEN_CD)
				OR	(@C_CHAKU_TODOFUKEN_CD  = '00' AND @C_CHAKU_AREA_CD != '00' AND KMO.AREA_CD  = @C_CHAKU_AREA_CD)
				)
			AND	(--発センター
					(RTRIM(@C_HATSU_SOSHIKI_CD) = '')
				OR	(KK.HASSIN_CENTER_CD = @C_HATSU_SOSHIKI_CD)
				)
			AND	(--成約区分
					(@C_SEIYAKU_KBN_OP = '0000')
				OR	(SUBSTRING(@C_SEIYAKU_KBN_OP,2,1) = '1' AND KK.SEIYAKU_KBN = '1')
				OR	(SUBSTRING(@C_SEIYAKU_KBN_OP,3,1) = '1' AND KK.SEIYAKU_KBN = '3')
				OR	(SUBSTRING(@C_SEIYAKU_KBN_OP,4,1) = '1' AND KK.SEIYAKU_KBN = '2')
				)
			AND	(
					(KK.HASSIN_CENTER_CD   = @IN_SOSHIKI_CD)
				OR	(KK.IRAISAKI_CENTER_CD = @IN_SOSHIKI_CD)
				OR	(KK.SEIYAKU_KBN        = '1')
				)
			--------------------------------------------------------
			-- 2010/10/22 Ins SYS_Ohki
			AND	(--協組織区分
					(@C_KYOSO_KBN = '000')
				OR	(SUBSTRING(@C_KYOSO_KBN,2,1)      = '1' AND KK.KYOSO_KBN   = '1')
				OR	(SUBSTRING(@C_KYOSO_KBN,3,1)      = '1' AND KK.KYOSO_KBN   = '0')
				)
			AND (	KK.KYOSO_KBN = '0' 
				OR (KK.KYOSO_KBN = '1' AND  SESSION.SOSHIKI_KBN = '3' AND HASSIN.SOSHIKI_KBN  = '3' AND SESSION.JYOBU_SOSHIKI_CD = HASSIN.JYOBU_SOSHIKI_CD)
				OR (KK.KYOSO_KBN = '1' AND  SESSION.SOSHIKI_KBN = '3' AND HASSIN.SOSHIKI_KBN  = '2' AND SESSION.JYOBU_SOSHIKI_CD = HASSIN.SOSHIKI_CD)
				OR (KK.KYOSO_KBN = '1' AND  SESSION.SOSHIKI_KBN = '2' AND HASSIN.SOSHIKI_KBN  = '2' AND SESSION.SOSHIKI_CD       = HASSIN.SOSHIKI_CD)
				OR (KK.KYOSO_KBN = '1' AND  SESSION.SOSHIKI_KBN = '2' AND HASSIN.SOSHIKI_KBN  = '3' AND SESSION.SOSHIKI_CD       = HASSIN.JYOBU_SOSHIKI_CD)
				OR (KK.KYOSO_KBN = '1' AND (SESSION.SOSHIKI_KBN = '1' OR  HASSIN.SOSHIKI_KBN  = '1'))
				)
			--------------------------------------------------------

			ORDER BY KMT.SAGYO_DT_FROM, KMT.SAGYO_DT_TO,KK.KYUKAKYUSYA_NO
	IF @@ERROR != 0
	BEGIN
		SET @ERR = @@ERROR
	END


	RETURN @ERR

END


GO

