USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[MAKE_IRAIMOTO_RYOKINDATA_ETC1]    Script Date: 07/31/2014 11:36:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[MAKE_IRAIMOTO_RYOKINDATA_ETC1](@UKETSUKE_NO CHAR(8),@SOSHIKI_CD CHAR(5)) AS
BEGIN
	DECLARE
		@IRAIMOTO_SOSHIKI_CD		CHAR(5),
		@DATA_COUNT					INT,
		@ERR						INT,
		@LOG_MSG					VARCHAR(200),
		@RYOKIN_1					DECIMAL(10),
		@RYOKIN_2					DECIMAL(10),
		@RYOKIN_3					DECIMAL(10),
		@RYOKIN_4					DECIMAL(10),
		@RYOKIN_5					DECIMAL(10),
		@RYOKIN_6					DECIMAL(10),
		@RYOKIN_SHOKEI				DECIMAL(10),
		@RYOKIN_NEBIKI_GK			DECIMAL(10),
		@RYOKIN_KEI					DECIMAL(10),
		@SHOHIZEI_RT				DECIMAL(10),
		@SHOHIZEI_GK				DECIMAL(10),
		@KOJINFUTAN_GK				DECIMAL(10),
		@SEIKYU_KEI					DECIMAL(10),
		@RYOKIN_NEBIKI_GK1			DECIMAL(10),
		@RYOKIN_NEBIKI_GKN			DECIMAL(10),
		@RYOKIN_NEBIKI_GKS			DECIMAL(10),
		@SYARYO_KBN_1				CHAR(2),
		@SYARYO_SU_1				smallint,
		@SYARYO_TANKA_1				DECIMAL(10),
		@SYARYO_KBN_2				CHAR(2),
		@SYARYO_SU_2				smallint,
		@SYARYO_TANKA_2				DECIMAL(10),
		@TSUMI_SAGYOIN_SU			smallint,
		@TSUMI_SAGYOIN_TANKA		DECIMAL(10),
		@OROSHI_SAGYOIN_SU			smallint,
		@OROSHI_SAGYOIN_TANKA		DECIMAL(10),
		@OPTION_MEI					VARCHAR(30),
		@SHOHIZEI_KBN				CHAR(1),
		@UPDATE_DT					CHAR(17),
		@UPDATE_TNT_ID				CHAR(10),
		@GAMEN_ID					CHAR(6)
	SELECT @ERR = 0
	--依頼元組織ＣＤ
	SELECT	@IRAIMOTO_SOSHIKI_CD = IRAIMOTO_SOSHIKI_CD
		FROM T_JUCHU_SYOSAI
		WHERE UKETSUKE_NO = @UKETSUKE_NO
		AND   SOSHIKI_CD  = @SOSHIKI_CD
	IF @@ROWCOUNT = 0
	BEGIN
		SELECT @ERR = -99
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_ERR
	END
--    SET @LOG_MSG = '依頼元組織ＣＤ='+@IRAIMOTO_SOSHIKI_CD+'を取得'
--    EXEC WRITE_PRCLOG 'RYOKINDATASP_1',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'D',@LOG_MSG
	--依頼元組織コードが登録されていない場合は処理を抜ける
	IF @IRAIMOTO_SOSHIKI_CD IS NULL
	BEGIN
		SELECT @ERR = -1
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_EXIT
	END
	--依頼元組織の料金データ存在をチェックする
	SELECT @DATA_COUNT = COUNT(*)
		FROM T_JUCHU_RYOKIN_M
		WHERE UKETSUKE_NO = @UKETSUKE_NO
		AND   SOSHIKI_CD  = @IRAIMOTO_SOSHIKI_CD
		AND   RYOKIN_SHUBETSU_CD IN ('50','60')
		AND   DELETE_FLG  = '0'
	--存在した場合は処理終了
	IF @DATA_COUNT != 0
	BEGIN
		SELECT @ERR = -1
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_EXIT
	END
--    SET @LOG_MSG = '依頼元組織の料金データ存在をチェック='+CONVERT(VARCHAR,@DATA_COUNT)
--    EXEC WRITE_PRCLOG 'RYOKINDATASP_1',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'D',@LOG_MSG
	DELETE FROM T_JUCHU_RYOKIN_M
		WHERE UKETSUKE_NO = @UKETSUKE_NO
		AND   SOSHIKI_CD  = @IRAIMOTO_SOSHIKI_CD
		AND   RYOKIN_SHUBETSU_CD IN ('50','60')
	SELECT @ERR = @@ERROR
	IF @ERR != 0
	BEGIN
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_ERR
	END
	--存在しない場合は料金情報、料金明細を作成する。
	--また、料金モードも同じに更新する。
	--料金明細の作成
	INSERT INTO T_JUCHU_RYOKIN_M (
			UKETSUKE_NO,
			SOSHIKI_CD,
			RYOKIN_SHUBETSU_CD,
			RYOKIN_SEQ,
			RYOKIN_KBN,
			SHOHIN_CD,
			RYOKIN_KOMOKU_MEI,
			RYOKIN_SU_1,
			RYOKIN_SU_2,
			BOX_SU,				--2004.07.07 Add By Kos
			RYOKIN_TANKA,
			URIAGE_GK,
			HAITATSU_FLG,
			KOJINFUTAN_GK,
			UPDATE_DT,
			UPDATE_TNT_ID,
			GAMEN_ID,
			DELETE_FLG
			)
	SELECT	UKETSUKE_NO,
			@IRAIMOTO_SOSHIKI_CD,
			RYOKIN_SHUBETSU_CD,
			RYOKIN_SEQ,
			RYOKIN_KBN,
			SHOHIN_CD,
			RYOKIN_KOMOKU_MEI,
			RYOKIN_SU_1,
			RYOKIN_SU_2,
			BOX_SU,				--2004.07.07 Add By Kos
			RYOKIN_TANKA,
			URIAGE_GK,
			HAITATSU_FLG,
			KOJINFUTAN_GK,
			UPDATE_DT,
			UPDATE_TNT_ID,
			GAMEN_ID,
			DELETE_FLG
	FROM	T_JUCHU_RYOKIN_M
	WHERE UKETSUKE_NO = @UKETSUKE_NO
	AND   SOSHIKI_CD  = @SOSHIKI_CD
	AND   RYOKIN_SHUBETSU_CD IN ('50','60')
	SELECT @ERR = @@ERROR
	IF @ERR != 0
	BEGIN
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_ERR
	END
--    SET @LOG_MSG = '依頼元組織の料金明細データ作成='+CONVERT(VARCHAR,@ERR)
--    EXEC WRITE_PRCLOG 'RYOKINDATASP_1',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'D',@LOG_MSG
	SELECT	@RYOKIN_1             = RYOKIN_1,
			@RYOKIN_2             = RYOKIN_2,
			@RYOKIN_3             = RYOKIN_3,
			@RYOKIN_4             = RYOKIN_4,
			@RYOKIN_5             = RYOKIN_5,
			@RYOKIN_6             = RYOKIN_6,
			@RYOKIN_SHOKEI        = RYOKIN_SHOKEI,
			@RYOKIN_NEBIKI_GK     = RYOKIN_NEBIKI_GK,
			@RYOKIN_KEI           = RYOKIN_KEI,
			@SHOHIZEI_RT          = SHOHIZEI_RT,
			@SHOHIZEI_GK          = SHOHIZEI_GK,
			@KOJINFUTAN_GK        = KOJINFUTAN_GK,
			@SEIKYU_KEI           = SEIKYU_KEI,
			@RYOKIN_NEBIKI_GK1    = RYOKIN_NEBIKI_GK1,
			@RYOKIN_NEBIKI_GKN    = RYOKIN_NEBIKI_GKN,		--2004.07.24 Add By Kotake
			@RYOKIN_NEBIKI_GKS    = RYOKIN_NEBIKI_GKS,		--2004.07.24 Add By Kotake
			@SYARYO_KBN_1         = SYARYO_KBN_1,
			@SYARYO_SU_1          = SYARYO_SU_1,
			@SYARYO_TANKA_1       = SYARYO_TANKA_1,
			@SYARYO_KBN_2         = SYARYO_KBN_2,
			@SYARYO_SU_2          = SYARYO_SU_2,
			@SYARYO_TANKA_2       = SYARYO_TANKA_2,
			@TSUMI_SAGYOIN_SU     = TSUMI_SAGYOIN_SU,
			@TSUMI_SAGYOIN_TANKA  = TSUMI_SAGYOIN_TANKA,
			@OROSHI_SAGYOIN_SU    = OROSHI_SAGYOIN_SU,
			@OROSHI_SAGYOIN_TANKA = OROSHI_SAGYOIN_TANKA,
			@OPTION_MEI           = OPTION_MEI,
			@SHOHIZEI_KBN         = SHOHIZEI_KBN,
			@UPDATE_DT            = UPDATE_DT,
			@UPDATE_TNT_ID        = UPDATE_TNT_ID,
			@GAMEN_ID             = GAMEN_ID
	FROM	T_JUCHU_RYOKIN
	WHERE UKETSUKE_NO = @UKETSUKE_NO
	AND   SOSHIKI_CD  = @SOSHIKI_CD
	--受注料金の更新（内手数料、粗利以外の項目更新する）
	UPDATE T_JUCHU_RYOKIN SET
				RYOKIN_1             = @RYOKIN_1,
				RYOKIN_2             = @RYOKIN_2,
				RYOKIN_3             = @RYOKIN_3,
				RYOKIN_4             = @RYOKIN_4,
				RYOKIN_5             = @RYOKIN_5,
				RYOKIN_6             = @RYOKIN_6,
				RYOKIN_SHOKEI        = @RYOKIN_SHOKEI,
				RYOKIN_NEBIKI_GK     = @RYOKIN_NEBIKI_GK,
				RYOKIN_KEI           = @RYOKIN_KEI,
				SHOHIZEI_RT          = @SHOHIZEI_RT,
				SHOHIZEI_GK          = @SHOHIZEI_GK,
				KOJINFUTAN_GK        = @KOJINFUTAN_GK,
				SEIKYU_KEI           = @SEIKYU_KEI,
				RYOKIN_NEBIKI_GK1    = @RYOKIN_NEBIKI_GK1,
				RYOKIN_NEBIKI_GKN    = @RYOKIN_NEBIKI_GKN,		--2004.07.24 Add By Kotake
				RYOKIN_NEBIKI_GKS    = @RYOKIN_NEBIKI_GKS,		--2004.07.24 Add By Kotake
				SYARYO_KBN_1         = @SYARYO_KBN_1,
				SYARYO_SU_1          = @SYARYO_SU_1,
				SYARYO_TANKA_1       = @SYARYO_TANKA_1,
				SYARYO_KBN_2         = @SYARYO_KBN_2,
				SYARYO_SU_2          = @SYARYO_SU_2,
				SYARYO_TANKA_2       = @SYARYO_TANKA_2,
				TSUMI_SAGYOIN_SU     = @TSUMI_SAGYOIN_SU,
				TSUMI_SAGYOIN_TANKA  = @TSUMI_SAGYOIN_TANKA,
				OROSHI_SAGYOIN_SU    = @OROSHI_SAGYOIN_SU,
				OROSHI_SAGYOIN_TANKA = @OROSHI_SAGYOIN_TANKA,
				OPTION_MEI           = @OPTION_MEI,
				SHOHIZEI_KBN         = @SHOHIZEI_KBN,
				UPDATE_DT            = @UPDATE_DT,
				UPDATE_TNT_ID        = @UPDATE_TNT_ID,
				GAMEN_ID             = @GAMEN_ID
		WHERE SOSHIKI_CD  = @IRAIMOTO_SOSHIKI_CD
		AND   UKETSUKE_NO = @UKETSUKE_NO
	SELECT @ERR = @@ERROR
	IF @ERR != 0
	BEGIN
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_ERR
	END
--    SET @LOG_MSG = '依頼元組織の料金情報データ更新='+CONVERT(VARCHAR,@ERR)
--    EXEC WRITE_PRCLOG 'RYOKINDATASP_1',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'D',@LOG_MSG
	SET @ERR = -999
MAKE_IRAIMOTO_RYOKINDATA_ETC1_EXIT:
	RETURN @ERR
MAKE_IRAIMOTO_RYOKINDATA_ETC1_ERR:
	IF @ERR = 0
		SET @LOG_MSG = '受注詳細データなし'
    ELSE
        SET @LOG_MSG = 'SQLエラー発生 Status:'+CONVERT(VARCHAR(10),@ERR)
	EXEC WRITE_PRCLOG 'RYOKINDATASP_1',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'E',@LOG_MSG
	GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC1_EXIT
END

GO

