USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[MAKE_IRAIMOTO_RYOKINDATA_ETC4]    Script Date: 07/31/2014 11:37:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[MAKE_IRAIMOTO_RYOKINDATA_ETC4](@UKETSUKE_NO CHAR(8),@SOSHIKI_CD CHAR(5)) AS
BEGIN
	DECLARE
		@IRAIMOTO_SOSHIKI_CD		CHAR(5),
		@ERR						INT,
		@LOG_MSG					VARCHAR(200),
		@ARARI_GK					DECIMAL(10),
		@UPDATE_DT					CHAR(17),
		@UPDATE_TNT_ID				CHAR(10),
		@GAMEN_ID					CHAR(6)
	SELECT @ERR = 0
	--依頼元組織ＣＤ及び粗利額を取得する
	SELECT	@IRAIMOTO_SOSHIKI_CD = TS.IRAIMOTO_SOSHIKI_CD,
			@ARARI_GK = TR1.RYOKIN_KEI - TR.RYOKIN_KEI
		FROM	T_JUCHU_SYOSAI TS
				INNER JOIN T_JUCHU_RYOKIN TR
					ON (TR.UKETSUKE_NO = TS.UKETSUKE_NO
					AND TR.SOSHIKI_CD  = TS.SOSHIKI_CD)
				INNER JOIN T_JUCHU_RYOKIN TR1
					ON (TR1.UKETSUKE_NO = TR.UKETSUKE_NO
					AND TR1.SOSHIKI_CD   = TS.IRAIMOTO_SOSHIKI_CD)
		WHERE	TS.UKETSUKE_NO = @UKETSUKE_NO
		AND		TS.SOSHIKI_CD  = @SOSHIKI_CD
	IF @@ROWCOUNT = 0
      GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC4_EXIT
	--受注料金の更新（粗利を更新する）
	UPDATE T_JUCHU_RYOKIN SET
			ARARI_GK             = @ARARI_GK,
			UPDATE_DT            = @UPDATE_DT,
			UPDATE_TNT_ID        = @UPDATE_TNT_ID,
			GAMEN_ID             = @GAMEN_ID
	WHERE SOSHIKI_CD  = @IRAIMOTO_SOSHIKI_CD
	AND   UKETSUKE_NO = @UKETSUKE_NO
	SELECT @ERR = @@ERROR
	IF @ERR != 0
	BEGIN
		GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC4_ERR
	END
MAKE_IRAIMOTO_RYOKINDATA_ETC4_EXIT:
	RETURN @ERR
MAKE_IRAIMOTO_RYOKINDATA_ETC4_ERR:
    SET @LOG_MSG = 'SQLエラー発生 Status:'+CONVERT(VARCHAR(10),@ERR)
	EXEC WRITE_PRCLOG 'RYOKINDATASP_4',@UKETSUKE_NO,@IRAIMOTO_SOSHIKI_CD,'E',@LOG_MSG
	GOTO MAKE_IRAIMOTO_RYOKINDATA_ETC4_EXIT
END

GO

