USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[RECORD_SP_ERROR]    Script Date: 07/31/2014 11:37:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[RECORD_SP_ERROR]
	@SP_NAME AS VARCHAR(50),
	@SOSHIKI_CD AS CHAR(5),
	@ERROR_CODE AS INT
AS
BEGIN
	INSERT INTO T_SP_ERROR(SP_NAME,SOSHIKI_CD,ERROR_CD) VALUES(@SP_NAME,@SOSHIKI_CD,@ERROR_CODE)
END


GO

