USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_AB0204]    Script Date: 07/31/2014 11:42:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/****** オブジェクト :  ストアド プロシージャ dbo.SP_AB0204    スクリプト日付 : 2005/02/21 16:57:56 ******/
/****** オブジェクト :  ストアド プロシージャ dbo.SP_AB0204    スクリプト日付 : 2005/02/21 13:36:59 ******/
/****** オブジェクト :  ストアド プロシージャ dbo.SP_AB0204    スクリプト日付 : 2005/02/17 9:26:18 ******/
/****** オブジェクト :  ストアド プロシージャ dbo.SP_AB0204    スクリプト日付 : 2005/02/16 16:15:31 ******/
/*
	受注ＣＳＶを料金明細で更新する
*/
CREATE            PROCEDURE [dbo].[SP_AB0204](
/******* Modified 2005.03.09 Akihisa Urushibara *******/
--	@依頼組織CD		AS CHAR(5)
	@依頼組織CD		AS CHAR(5),
	@ERROR AS INT OUTPUT
/******* Modified 2005.03.09 Akihisa Urushibara *******/
)
AS
DECLARE
	@ITEMCNT		AS INTEGER,
	@料金区分		AS CHAR(4),
	@料金種別		AS CHAR(2),
	@料金枝番		AS SMALLINT
BEGIN
	SELECT @ITEMCNT = 0
	WHILE 1=1
	BEGIN
		SELECT @料金区分 =
		CASE @ITEMCNT
			WHEN 0		THEN '1019'
			WHEN 1		THEN '1000'
			WHEN 2		THEN '1001'
			WHEN 3		THEN '1002'
			WHEN 4		THEN '1003'
			WHEN 5		THEN '1004'
			WHEN 6		THEN '1005'
			WHEN 7		THEN '1006'
			WHEN 8		THEN '1008'
			WHEN 9		THEN '1010'
			WHEN 10		THEN '1012'
			WHEN 11		THEN '1101'
			WHEN 12		THEN '1102'
			WHEN 13		THEN '1201'
			WHEN 14		THEN '1202'
			WHEN 15		THEN '2001'
			WHEN 16		THEN '2002'
			WHEN 17		THEN '2003'
			WHEN 18		THEN '2004'
			WHEN 19		THEN '2005'
			WHEN 20		THEN '2006'
			WHEN 21		THEN '3001'
			WHEN 22		THEN '3002'
			WHEN 23		THEN '3003'
			WHEN 24		THEN '3004'
			WHEN 25		THEN '7001'
			WHEN 26		THEN '7002'
			WHEN 27		THEN '7003'
			ELSE '9999'
		END
		IF @料金区分 = '9999' 
			BREAK
		UPDATE W_HIKKOSHI_CSV_NORMAL
--2005/03/07 ONO START
--		SET		SURYO_KOBATO		= (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(JRM.BOX_SU,0.0) ELSE SURYO_KOBATO END)
--			,	SURYO_KT			= (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KT END)
--			,	SURYO_1T			= (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_1T END)
--			,	SURYO_2T			= (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_2T END)
--			,	SURYO_3T			= (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_3T END)
--			,	SURYO_4T			= (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_4T END)
--			,	SURYO_5T			= (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_5T END)
--			,	SURYO_6T			= (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_6T END)
--			,	SURYO_8T			= (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_8T END)
--			,	SURYO_10T			= (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_10T END)
--			,	SURYO_12T			= (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_12T END)
--			,	SURYO_CT			= (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_CT END)
--			,	SURYO_ETC			= (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_ETC END)
--			,	URIAGE_KOBATO		= (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KOBATO END)
--			,	URIAGE_KT			= (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KT END)
--			,	URIAGE_1T			= (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_1T END)
--			,	URIAGE_2T			= (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_2T END)
--			,	URIAGE_3T			= (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_3T END)
--			,	URIAGE_4T			= (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_4T END)
--			,	URIAGE_5T			= (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_5T END)
--			,	URIAGE_6T			= (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_6T END)
--			,	URIAGE_8T			= (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_8T END)
--			,	URIAGE_10T			= (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_10T END)
--			,	URIAGE_12T			= (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_12T END)
--			,	URIAGE_CT			= (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_CT END)
--			,	URIAGE_ETC			= (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_ETC END)
--			,	URIAGE_TOME			= (CASE JRM.RYOKIN_KBN WHEN '1201' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TOME END)
--			,	URIAGE_YOKO			= (CASE JRM.RYOKIN_KBN WHEN '1202' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YOKO END)
--			,	SURYO_NIEKI_TSUMI	= (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_TSUMI END)
--			,	URIAGE_NIEKI_TSUMI	= (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_TSUMI END)
--			,	NIEKI_TSUMI_CD		= (CASE JRM.RYOKIN_KBN WHEN '2001' THEN SHOHIN_CD ELSE NIEKI_TSUMI_CD END)
--			,	NIEKI_TSUMI_MEI		= (CASE JRM.RYOKIN_KBN
--											WHEN '2001' THEN
--												(CASE SHOHIN_CD
--													WHEN '1' THEN '４時間制'
--													WHEN '2' THEN '８時間制'
--													WHEN '3' THEN '１時間超'
--													WHEN '4' THEN '２時間超'
--													WHEN '5' THEN '３時間超'
--													WHEN '6' THEN '４時間超'
--													WHEN '7' THEN '５時間超'
--													WHEN '8' THEN '６時間超'
--													WHEN '9' THEN '小鳩'
--													ELSE ''
--												END)
--											ELSE NIEKI_TSUMI_MEI
--										  END)
--			,	SURYO_NIEKI_OROSHI	= (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_OROSHI END)
--			,	URIAGE_NIEKI_OROSHI	= (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_OROSHI END)
--			,	NIEKI_OROSHI_CD		= (CASE JRM.RYOKIN_KBN WHEN '2002' THEN SHOHIN_CD ELSE NIEKI_OROSHI_CD END)
--			,	NIEKI_OROSHI_MEI	= (CASE JRM.RYOKIN_KBN
--											WHEN '2002' THEN
--												(CASE SHOHIN_CD
--													WHEN '1' THEN '４時間制'
--													WHEN '2' THEN '８時間制'
--													WHEN '3' THEN '１時間超'
--													WHEN '4' THEN '２時間超'
--													WHEN '5' THEN '３時間超'
--													WHEN '6' THEN '４時間超'
--													WHEN '7' THEN '５時間超'
--													WHEN '8' THEN '６時間超'
--													WHEN '9' THEN '小鳩'
--													ELSE ''
--												END)
--											ELSE NIEKI_OROSHI_MEI
--										  END)
--			,	SURYO_KONPO			= (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KONPO END)
--			,	URIAGE_KONPO		= (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KONPO END)
--			,	KONPO_CD			= (CASE JRM.RYOKIN_KBN WHEN '2003' THEN SHOHIN_CD ELSE KONPO_CD END)
--			,	KONPO_MEI			= (CASE JRM.RYOKIN_KBN
--											WHEN '2003' THEN
--												(CASE SHOHIN_CD
--													WHEN '1' THEN '４時間制'
--													WHEN '2' THEN '８時間制'
--													WHEN '3' THEN '１時間超'
--													WHEN '4' THEN '２時間超'
--													WHEN '5' THEN '３時間超'
--													WHEN '6' THEN '４時間超'
--													WHEN '7' THEN '５時間超'
--													WHEN '8' THEN '６時間超'
--													WHEN '9' THEN '小鳩'
--													ELSE ''
--												END)
--											ELSE KONPO_MEI
--										  END)
--			,	SURYO_KAIKON		= (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KAIKON END)
--			,	URIAGE_KAIKON		= (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KAIKON END)
--			,	KAIKON_CD			= (CASE JRM.RYOKIN_KBN WHEN '2004' THEN SHOHIN_CD ELSE KAIKON_CD END)
--			,	KAIKON_MEI			= (CASE JRM.RYOKIN_KBN
--											WHEN '2004' THEN
--												(CASE SHOHIN_CD
--													WHEN '1' THEN '４時間制'
--													WHEN '2' THEN '８時間制'
--													WHEN '3' THEN '１時間超'
--													WHEN '4' THEN '２時間超'
--													WHEN '5' THEN '３時間超'
--													WHEN '6' THEN '４時間超'
--													WHEN '7' THEN '５時間超'
--													WHEN '8' THEN '６時間超'
--													WHEN '9' THEN '小鳩'
--													ELSE ''
--												END)
--											ELSE KAIKON_MEI
--										  END)
--			,	SURYO_JIKANGAI		= (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_JIKANGAI END)
--			,	URIAGE_JIKANGAI		= (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_JIKANGAI END)
--			,	JIKANGAI_CD			= (CASE JRM.RYOKIN_KBN WHEN '2005' THEN SHOHIN_CD ELSE JIKANGAI_CD END)
--			,	JIKANGAI_MEI		= (CASE JRM.RYOKIN_KBN
--											WHEN '2005' THEN
--												(CASE SHOHIN_CD
--													WHEN '1' THEN '４時間制'
--													WHEN '2' THEN '８時間制'
--													WHEN '3' THEN '１時間超'
--													WHEN '4' THEN '２時間超'
--													WHEN '5' THEN '３時間超'
--													WHEN '6' THEN '４時間超'
--													WHEN '7' THEN '５時間超'
--													WHEN '8' THEN '６時間超'
--													WHEN '9' THEN '小鳩'
--													ELSE ''
--												END)
--											ELSE JIKANGAI_MEI
--										  END)
--			,	SURYO_YUSO			= (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_YUSO END)
--			,	URIAGE_YUSO			= (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YUSO END)
--			,	SURYO_OPTION_1		= (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_1 END)
--			,	URIAGE_OPTION_1		= (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_1 END)
--			,	SURYO_OPTION_2		= (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_2 END)
--			,	URIAGE_OPTION_2		= (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_2 END)
--			,	SURYO_OPTION_3		= (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_3 END)
--			,	URIAGE_OPTION_3		= (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_3 END)
--			,	SURYO_OPTION_4		= (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_4 END)
--			,	URIAGE_OPTION_4		= (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_4 END)
--			,	URIAGE_TATEKAE_1	= (CASE JRM.RYOKIN_KBN WHEN '7001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_1 END)
--			,	URIAGE_TATEKAE_2	= (CASE JRM.RYOKIN_KBN WHEN '7002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_2 END)
--			,	URIAGE_TATEKAE_3	= (CASE JRM.RYOKIN_KBN WHEN '7003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_3 END)
		SET		SURYO_KOBATO		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(JRM.BOX_SU,0.0) ELSE SURYO_KOBATO END) 
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(JRM.BOX_SU,0.0) ELSE SURYO_KOBATO END) ELSE 0 END END
			,	SURYO_KT			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KT END) 
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KT END) ELSE 0 END END
			,	SURYO_1T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_1T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_1T END) ELSE 0 END END
			,	SURYO_2T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_2T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_2T END) ELSE 0 END END
			,	SURYO_3T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_3T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_3T END) ELSE 0 END END
			,	SURYO_4T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_4T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_4T END) ELSE 0 END END
			,	SURYO_5T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_5T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_5T END) ELSE 0 END END
			,	SURYO_6T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_6T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_6T END) ELSE 0 END END
			,	SURYO_8T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_8T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_8T END) ELSE 0 END END
			,	SURYO_10T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_10T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_10T END) ELSE 0 END END
			,	SURYO_12T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_12T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_12T END) ELSE 0 END END
			,	SURYO_CT			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_CT END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_CT END) ELSE 0 END END
			,	SURYO_ETC			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_ETC END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_ETC END) ELSE 0 END END
			,	URIAGE_KOBATO		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KOBATO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1019' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KOBATO END) ELSE 0 END END
			,	URIAGE_KT			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KT END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1000' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KT END) ELSE 0 END END
			,	URIAGE_1T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_1T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_1T END) ELSE 0 END END
			,	URIAGE_2T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_2T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_2T END) ELSE 0 END END
			,	URIAGE_3T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_3T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_3T END) ELSE 0 END END
			,	URIAGE_4T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_4T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_4T END) ELSE 0 END END
			,	URIAGE_5T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_5T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_5T END) ELSE 0 END END
			,	URIAGE_6T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_6T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_6T END) ELSE 0 END END
			,	URIAGE_8T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_8T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1008' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_8T END) ELSE 0 END END
			,	URIAGE_10T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_10T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1010' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_10T END) ELSE 0 END END
			,	URIAGE_12T			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_12T END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1012' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_12T END) ELSE 0 END END
			,	URIAGE_CT			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_CT END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1101' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_CT END) ELSE 0 END END
			,	URIAGE_ETC			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_ETC END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1102' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_ETC END) ELSE 0 END END
			,	URIAGE_TOME			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1201' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TOME END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1201' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TOME END) ELSE 0 END END
			,	URIAGE_YOKO			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '1202' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YOKO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '1202' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YOKO END) ELSE 0 END END
			,	SURYO_NIEKI_TSUMI	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_TSUMI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_TSUMI END) ELSE 0 END END
			,	URIAGE_NIEKI_TSUMI	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_TSUMI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_TSUMI END) ELSE 0 END END
			,	NIEKI_TSUMI_CD		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN SHOHIN_CD ELSE NIEKI_TSUMI_CD END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2001' THEN SHOHIN_CD ELSE NIEKI_TSUMI_CD END) ELSE '' END END
			,	NIEKI_TSUMI_MEI		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2001' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE NIEKI_TSUMI_MEI
											  END) 
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2001' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE NIEKI_TSUMI_MEI
											  END) ELSE '' END END
			,	SURYO_NIEKI_OROSHI	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_OROSHI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_NIEKI_OROSHI END) ELSE 0 END END
			,	URIAGE_NIEKI_OROSHI	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_OROSHI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_NIEKI_OROSHI END) ELSE 0 END END
			,	NIEKI_OROSHI_CD		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN SHOHIN_CD ELSE NIEKI_OROSHI_CD END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2002' THEN SHOHIN_CD ELSE NIEKI_OROSHI_CD END) ELSE '' END END
			,	NIEKI_OROSHI_MEI	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2002' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE NIEKI_OROSHI_MEI
											  END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2002' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE NIEKI_OROSHI_MEI
											  END) ELSE '' END END
			,	SURYO_KONPO			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KONPO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KONPO END) ELSE 0 END END
			,	URIAGE_KONPO		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KONPO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KONPO END) ELSE 0 END END
			,	KONPO_CD			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN SHOHIN_CD ELSE KONPO_CD END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2003' THEN SHOHIN_CD ELSE KONPO_CD END) ELSE '' END END
			,	KONPO_MEI			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2003' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE KONPO_MEI
											  END) 
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2003' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE KONPO_MEI
											  END) ELSE '' END END
			,	SURYO_KAIKON		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KAIKON END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_KAIKON END) ELSE 0 END END
			,	URIAGE_KAIKON		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KAIKON END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_KAIKON END) ELSE 0 END END
			,	KAIKON_CD			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN SHOHIN_CD ELSE KAIKON_CD END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2004' THEN SHOHIN_CD ELSE KAIKON_CD END) ELSE '' END END
			,	KAIKON_MEI			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2004' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE KAIKON_MEI
											  END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2004' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE KAIKON_MEI
											  END) ELSE '' END END
			,	SURYO_JIKANGAI		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_JIKANGAI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_JIKANGAI END) ELSE 0 END END
			,	URIAGE_JIKANGAI		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_JIKANGAI END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_JIKANGAI END) ELSE 0 END END
			,	JIKANGAI_CD			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN SHOHIN_CD ELSE JIKANGAI_CD END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2005' THEN SHOHIN_CD ELSE JIKANGAI_CD END) ELSE '' END END
			,	JIKANGAI_MEI		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2005' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE JIKANGAI_MEI
											  END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN 
											(CASE JRM.RYOKIN_KBN
												WHEN '2005' THEN
													(CASE SHOHIN_CD
														WHEN '1' THEN '４時間制'
														WHEN '2' THEN '８時間制'
														WHEN '3' THEN '１時間超'
														WHEN '4' THEN '２時間超'
														WHEN '5' THEN '３時間超'
														WHEN '6' THEN '４時間超'
														WHEN '7' THEN '５時間超'
														WHEN '8' THEN '６時間超'
														WHEN '9' THEN '小鳩'
														ELSE ''
													END)
												ELSE JIKANGAI_MEI
											  END) ELSE '' END END
			,	SURYO_YUSO			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_YUSO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_YUSO END) ELSE 0 END END
			,	URIAGE_YUSO			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YUSO END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '2006' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_YUSO END) ELSE 0 END END
			,	SURYO_OPTION_1		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_1 END) ELSE 0 END END
			,	URIAGE_OPTION_1		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_1 END) ELSE 0 END END
			,	SURYO_OPTION_2		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_2 END) ELSE 0 END END
			,	URIAGE_OPTION_2		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_2 END) ELSE 0 END END
			,	SURYO_OPTION_3		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_3 END) ELSE 0 END END
			,	URIAGE_OPTION_3		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_3 END) ELSE 0 END END
			,	SURYO_OPTION_4		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_4 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_OPTION_4 END) ELSE 0 END END
			,	URIAGE_OPTION_4		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_4 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '3004' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_OPTION_4 END) ELSE 0 END END
			,	URIAGE_TATEKAE_1	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '7001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '7001' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_1 END) ELSE 0 END END
			,	URIAGE_TATEKAE_2	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '7002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '7002' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_2 END) ELSE 0 END END
			,	URIAGE_TATEKAE_3	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_KBN WHEN '7003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_KBN WHEN '7003' THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TATEKAE_3 END) ELSE 0 END END
--2005/03/07 ONO END
		FROM	W_HIKKOSHI_CSV_NORMAL AS WC
--2005/03/07 ONO START
				INNER JOIN T_JUCHU_KIHON AS JK
				ON JK.UKETSUKE_NO = WC.UKETSUKE_NO
--2005/03/07 ONO END
				LEFT JOIN T_JUCHU_RYOKIN_M AS JRM
				ON	JRM.UKETSUKE_NO	= WC.UKETSUKE_NO
				AND	JRM.SOSHIKI_CD	= WC.SOSHIKI_CD
				AND JRM.RYOKIN_KBN	= @料金区分
--2005/03/07 ONO START
				LEFT JOIN T_JUCHU_RYOKIN AS JR
				ON	JR.UKETSUKE_NO	= WC.UKETSUKE_NO
				AND	JR.SOSHIKI_CD	= WC.SOSHIKI_CD
--2005/03/07 ONO END
		WHERE	WC.IRAI_SOSHIKI_CD	= @依頼組織CD
/******* Added 2005.03.09 Akihisa Urushibara *******/
		SET @ERROR = @@ERROR
		IF @ERROR > 0
		BEGIN
			RETURN
		END
/******* Added 2005.03.09 Akihisa Urushibara *******/
		SELECT @ITEMCNT = @ITEMCNT + 1
	END
	SELECT @料金枝番 = 0
	WHILE 1=1
	BEGIN
		IF @料金枝番 > 7 
			BREAK
		UPDATE W_HIKKOSHI_CSV_NORMAL
--2005/03/07 ONO START
--		SET		TEHAI_MEI_0			= (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_0 END)
--			,	SURYO_TEHAI_0		= (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_0 END)
--			,	URIAGE_TEHAI_0		= (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_0 END)
--			,	TEHAI_MEI_1			= (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_1 END)
--			,	SURYO_TEHAI_1		= (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_1 END)
--			,	URIAGE_TEHAI_1		= (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_1 END)
--			,	TEHAI_MEI_2			= (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_2 END)
--			,	SURYO_TEHAI_2		= (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_2 END)
--			,	URIAGE_TEHAI_2		= (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_2 END)
--			,	TEHAI_MEI_3			= (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_3 END)
--			,	SURYO_TEHAI_3		= (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_3 END)
--			,	URIAGE_TEHAI_3		= (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_3 END)
--			,	TEHAI_MEI_4			= (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_4 END)
--			,	SURYO_TEHAI_4		= (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_4 END)
--			,	URIAGE_TEHAI_4		= (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_4 END)
--			,	TEHAI_MEI_5			= (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_5 END)
--			,	SURYO_TEHAI_5		= (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_5 END)
--			,	URIAGE_TEHAI_5		= (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_5 END)
--			,	TEHAI_MEI_6			= (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_6 END)
--			,	SURYO_TEHAI_6		= (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_6 END)
--			,	URIAGE_TEHAI_6		= (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_6 END)
--			,	TEHAI_MEI_7			= (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_7 END)
--			,	SURYO_TEHAI_7		= (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_7 END)
--			,	URIAGE_TEHAI_7		= (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_7 END)
		SET		TEHAI_MEI_0			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_0 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_0 END) ELSE '' END END
			,	SURYO_TEHAI_0		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_0 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_0 END) ELSE 0 END END
			,	URIAGE_TEHAI_0		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_0 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 0 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_0 END) ELSE 0 END END
			,	TEHAI_MEI_1			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_1 END) ELSE '' END END
			,	SURYO_TEHAI_1		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_1 END) ELSE 0 END END
			,	URIAGE_TEHAI_1		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_1 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 1 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_1 END) ELSE 0 END END
			,	TEHAI_MEI_2			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_2 END) ELSE '' END END
			,	SURYO_TEHAI_2		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_2 END) ELSE 0 END END
			,	URIAGE_TEHAI_2		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_2 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 2 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_2 END) ELSE 0 END END
			,	TEHAI_MEI_3			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_3 END) ELSE '' END END
			,	SURYO_TEHAI_3		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_3 END) ELSE 0 END END
			,	URIAGE_TEHAI_3		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_3 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 3 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_3 END) ELSE 0 END END
			,	TEHAI_MEI_4			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_4 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_4 END) ELSE '' END END
			,	SURYO_TEHAI_4		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_4 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_4 END) ELSE 0 END END
			,	URIAGE_TEHAI_4		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_4 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 4 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_4 END) ELSE 0 END END
			,	TEHAI_MEI_5			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_5 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_5 END) ELSE '' END END
			,	SURYO_TEHAI_5		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_5 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_5 END) ELSE 0 END END
			,	URIAGE_TEHAI_5		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_5 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 5 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_5 END) ELSE 0 END END
			,	TEHAI_MEI_6			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_6 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_6 END) ELSE '' END END
			,	SURYO_TEHAI_6		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_6 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_6 END) ELSE 0 END END
			,	URIAGE_TEHAI_6		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_6 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 6 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_6 END) ELSE 0 END END
			,	TEHAI_MEI_7			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_7 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_KOMOKU_MEI,'') ELSE TEHAI_MEI_7 END) ELSE '' END END
			,	SURYO_TEHAI_7		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_7 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(RYOKIN_SU_1,0) ELSE SURYO_TEHAI_7 END) ELSE 0 END END
			,	URIAGE_TEHAI_7		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_7 END)
										ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN (CASE JRM.RYOKIN_SEQ WHEN 7 THEN ISNULL(URIAGE_GK,0) ELSE URIAGE_TEHAI_7 END) ELSE 0 END END
--2005/03/07 ONO END
		FROM	W_HIKKOSHI_CSV_NORMAL AS WC
--2005/03/07 ONO START
				INNER JOIN T_JUCHU_KIHON AS JK
				ON JK.UKETSUKE_NO = WC.UKETSUKE_NO
--2005/03/07 ONO END
				LEFT JOIN T_JUCHU_RYOKIN_M AS JRM
				ON	JRM.UKETSUKE_NO			= WC.UKETSUKE_NO
				AND	JRM.SOSHIKI_CD			= WC.SOSHIKI_CD
				AND JRM.RYOKIN_SHUBETSU_CD	= '40'
				AND JRM.RYOKIN_SEQ			= @料金枝番
--2005/03/07 ONO START
				LEFT JOIN T_JUCHU_RYOKIN AS JR
				ON	JR.UKETSUKE_NO			= WC.UKETSUKE_NO
				AND	JR.SOSHIKI_CD			= WC.SOSHIKI_CD
--2005/03/07 ONO END
		WHERE	WC.IRAI_SOSHIKI_CD	= @依頼組織CD
/******* Added 2005.03.09 Akihisa Urushibara *******/
		SET @ERROR = @@ERROR
		IF @ERROR > 0
		BEGIN
			RETURN
		END
/******* Added 2005.03.09 Akihisa Urushibara *******/
		SELECT @料金枝番 = @料金枝番 + 1
	END
	UPDATE W_HIKKOSHI_CSV_NORMAL
--2005/03/07 ONO START
--	SET		RYOKIN_1			= ISNULL(JR.RYOKIN_1,0)
--		,	RYOKIN_2			= ISNULL(JR.RYOKIN_2,0)
--		,	RYOKIN_3			= ISNULL(JR.RYOKIN_3,0)
--		,	RYOKIN_4			= ISNULL(JR.RYOKIN_4,0)
--		,	RYOKIN_5			= ISNULL(JR.RYOKIN_5,0)
--		,	RYOKIN_6			= ISNULL(JR.RYOKIN_6,0)
--		,	KOJINFUTAN_GK		= ISNULL(JR.KOJINFUTAN_GK,0)
--		,	RYOKIN_SHOKEI		= ISNULL(JR.RYOKIN_SHOKEI,0)
--		,	RYOKIN_NEBIKI_GK1	= ISNULL(JR.RYOKIN_NEBIKI_GK1,0)
--		,	SHOHIZEI_GK			= ISNULL(JR.SHOHIZEI_GK,0)
--		,	RYOKIN_NEBIKI_GK	= ISNULL(JR.RYOKIN_NEBIKI_GK,0)
--		,	RYOKIN_KEI			= ISNULL(JR.RYOKIN_KEI,0)
--		,	RYOKIN_TESURYO_GK	= ISNULL(JR.RYOKIN_TESURYO_GK,0)
	SET		RYOKIN_1			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_1,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_1,0) ELSE 0 END END
		,	RYOKIN_2			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_2,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_2,0) ELSE 0 END END
		,	RYOKIN_3			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_3,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_3,0) ELSE 0 END END
		,	RYOKIN_4			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_4,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_4,0) ELSE 0 END END
		,	RYOKIN_5			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_5,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_5,0) ELSE 0 END END
		,	RYOKIN_6			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_6,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_6,0) ELSE 0 END END
		,	KOJINFUTAN_GK		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.KOJINFUTAN_GK,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.KOJINFUTAN_GK,0) ELSE 0 END END
		,	RYOKIN_SHOKEI		= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_SHOKEI,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_SHOKEI,0) ELSE 0 END END
		,	RYOKIN_NEBIKI_GK1	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_NEBIKI_GK1,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_NEBIKI_GK1,0) ELSE 0 END END
		,	SHOHIZEI_GK			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.SHOHIZEI_GK,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.SHOHIZEI_GK,0) ELSE 0 END END
		,	RYOKIN_NEBIKI_GK	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_NEBIKI_GK,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_NEBIKI_GK,0) ELSE 0 END END
		,	RYOKIN_KEI			= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_KEI,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_KEI,0) ELSE 0 END END
		,	RYOKIN_TESURYO_GK	= CASE ISNULL(JR.RYOKIN_INPUT_FLG,'0') WHEN '1' THEN ISNULL(JR.RYOKIN_TESURYO_GK,0)
									ELSE CASE ISNULL(JK.INPUT_SBT_CD,'0') WHEN '2' THEN ISNULL(JR.RYOKIN_TESURYO_GK,0) ELSE 0 END END
--2005/03/07 ONO END
	FROM	W_HIKKOSHI_CSV_NORMAL AS WC
--2005/03/07 ONO START
			INNER JOIN T_JUCHU_KIHON AS JK
			ON JK.UKETSUKE_NO = WC.UKETSUKE_NO
--2005/03/07 ONO END
			LEFT JOIN T_JUCHU_RYOKIN AS JR
			ON	JR.UKETSUKE_NO	= WC.UKETSUKE_NO
			AND	JR.SOSHIKI_CD	= WC.SOSHIKI_CD
	WHERE	WC.IRAI_SOSHIKI_CD	= @依頼組織CD
/******* Added 2005.03.09 Akihisa Urushibara *******/
	SET @ERROR = @@ERROR
/******* Added 2005.03.09 Akihisa Urushibara *******/
END



GO

