USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_COM_SAVE_KENSAKU_CONDITION]    Script Date: 07/31/2014 11:44:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_COM_SAVE_KENSAKU_CONDITION](
	@IN_SESSION_ID        AS CHAR(30),
    @IN_GAMEN_ID          AS CHAR(6),
    @IN_KENSAKU_CONDITION AS VARCHAR(256)
)
AS
DECLARE
	@ERR INT
BEGIN

	SET @ERR = 0

	DELETE W_COM_KENSAKU_CND
		WHERE SESSION_CD = @IN_SESSION_ID
		AND   GAMEN_ID   = @IN_GAMEN_ID

	IF RTRIM(@IN_KENSAKU_CONDITION) = '' OR @IN_KENSAKU_CONDITION IS NULL
		GOTO SP_COM_SAVE_KENSAKU_CONDITION_EXIT

	INSERT INTO W_COM_KENSAKU_CND (
				SESSION_CD,
				GAMEN_ID,
				KENSAKU_CONDITION
				)
		VALUES (
				@IN_SESSION_ID,
				@IN_GAMEN_ID,
				@IN_KENSAKU_CONDITION
				);
	IF @@ERROR != 0
	BEGIN
		SET @ERR = @@ERROR
	END

SP_COM_SAVE_KENSAKU_CONDITION_EXIT:
	RETURN @ERR

END

GO

