USE [HATO2]
GO

/****** Object:  StoredProcedure [dbo].[SP_KYUKAKYUSYA_KENSAKU_MANAGER]    Script Date: 07/31/2014 11:48:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_KYUKAKYUSYA_KENSAKU_MANAGER](
	@IN_SESSION_ID         AS VARCHAR(30),
	@IN_GAMEN_ID           AS CHAR(6),
	@IN_USER_ID            AS CHAR(10),
	@IN_KYUKAKYUSYA_NO     AS CHAR(8),
	@IN_KYUKAKYUSYA_KBN    AS CHAR(1),
	@IN_SAGYO_DATE_F       AS CHAR(8),
	@IN_SAGYO_DATE_T       AS CHAR(8),
	@IN_HATSU_AREA_CD      AS CHAR(2),
	@IN_HATSU_TODOFUKEN_CD AS CHAR(2),
	@IN_CHAKU_AREA_CD      AS CHAR(2),
	@IN_CHAKU_TODOFUKEN_CD AS CHAR(2),
	@IN_HATSU_SOSHIKI_CD   AS CHAR(5),
	@IN_SEIYAKU_KBN_OP     AS CHAR(4),
	@IN_KYOSO_KBN		   AS CHAR(3),
	@IN_BUTTON_FLG         AS CHAR(1)
)
AS
DECLARE
	@ERR                   INT,
	@V_KENSAKU_CONDITION   VARCHAR(256),
	@C_SOSHIKI_CD          CHAR(5),
	@C_KYUKAKYUSYA_NO      CHAR(8),
	@C_KYUKAKYUSYA_KBN     CHAR(1),
	@C_SAGYO_DATE_F        CHAR(8),
	@C_SAGYO_DATE_T        CHAR(8),
	@C_HATSU_AREA_CD       CHAR(2),
	@C_HATSU_TODOFUKEN_CD  CHAR(2),
	@C_CHAKU_AREA_CD       CHAR(2),
	@C_CHAKU_TODOFUKEN_CD  CHAR(2),
	@C_HATSU_SOSHIKI_CD    CHAR(5),
	@C_SEIYAKU_KBN_OP      CHAR(4),
	@C_KYOSO_KBN		   CHAR(3),
	@C_BUTTON_FLG          CHAR(1)
	
BEGIN

	SET @C_KYUKAKYUSYA_NO     = ''+RTRIM(@IN_KYUKAKYUSYA_NO)
	SET @C_KYUKAKYUSYA_KBN    = ''+RTRIM(@IN_KYUKAKYUSYA_KBN)
	SET @C_SAGYO_DATE_F       = ''+RTRIM(@IN_SAGYO_DATE_F)
	SET @C_SAGYO_DATE_T       = ''+RTRIM(@IN_SAGYO_DATE_T)
	SET @C_HATSU_AREA_CD      = ''+RTRIM(@IN_HATSU_AREA_CD)
	SET @C_HATSU_TODOFUKEN_CD = ''+RTRIM(@IN_HATSU_TODOFUKEN_CD)
	SET @C_CHAKU_AREA_CD      = ''+RTRIM(@IN_CHAKU_AREA_CD)
	SET @C_CHAKU_TODOFUKEN_CD = ''+RTRIM(@IN_CHAKU_TODOFUKEN_CD)
	SET @C_HATSU_SOSHIKI_CD   = ''+RTRIM(@IN_HATSU_SOSHIKI_CD)
	SET @C_SEIYAKU_KBN_OP     = ''+RTRIM(@IN_SEIYAKU_KBN_OP)

	-- ========== Str 2010/10/22 Ins SYS_Ohki ==========
	SET @C_KYOSO_KBN          = ''+RTRIM(@IN_KYOSO_KBN)
	-- ========== End 2010/10/22 Ins SYS_Ohki ==========

	SET @C_BUTTON_FLG         = ''+RTRIM(@IN_BUTTON_FLG)
	

	--ユーザＩＤの組織属性を取得する
	SELECT
		@C_SOSHIKI_CD  = MU.SOSHIKI_CD
		FROM
			M_USER_KANRI MU
			INNER JOIN M_SOSHIKI MS
				ON (MS.SOSHIKI_CD = MU.SOSHIKI_CD)
		WHERE USER_ID = @IN_USER_ID

	--検索条件を結合する
	SET @V_KENSAKU_CONDITION = ''
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + RTRIM(@C_KYUKAKYUSYA_NO) + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_KYUKAKYUSYA_KBN + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + RTRIM(@C_SAGYO_DATE_F) + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + RTRIM(@C_SAGYO_DATE_T) + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_HATSU_AREA_CD + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_HATSU_TODOFUKEN_CD + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_CHAKU_AREA_CD + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_CHAKU_TODOFUKEN_CD + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + RTRIM(@C_HATSU_SOSHIKI_CD) + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_SEIYAKU_KBN_OP + ','
	
	-- ========== Str 2010/10/22 Upd SYS_Ohki ==========
	-- SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_BUTTON_FLG
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_BUTTON_FLG + ','
	SET @V_KENSAKU_CONDITION = @V_KENSAKU_CONDITION + @C_KYOSO_KBN
	-- ========== End 2010/10/22 Upd SYS_Ohki ==========

	SET NOCOUNT ON

	--検索条件を保持する
	EXEC @ERR = SP_COM_SAVE_KENSAKU_CONDITION @IN_SESSION_ID,@IN_GAMEN_ID,@V_KENSAKU_CONDITION
	IF @ERR != 0
	BEGIN
		GOTO SP_KYUKAKYUSYA_KENSAKU_MANAGER_EXIT
	END

	--全件ボタンクリック
	IF @C_BUTTON_FLG = '1'
	BEGIN
		EXEC @ERR = SP_KYUKAKYUSYA_KENSAKU_ALL @IN_SESSION_ID,@C_SOSHIKI_CD
	END

	--検索ボタンクリック
	IF @C_BUTTON_FLG = '2'
	BEGIN
		--求貨求車番号指定
		IF RTRIM(@C_KYUKAKYUSYA_NO) != ''
		BEGIN
			EXEC @ERR = SP_KYUKAKYUSYA_KENSAKU_KYUKAKYUSYA_NO @IN_SESSION_ID,@C_KYUKAKYUSYA_NO,@C_SOSHIKI_CD
		END
		ELSE
		BEGIN
			EXEC @ERR = SP_KYUKAKYUSYA_KENSAKU_OTHER
									@IN_SESSION_ID       ,
									@C_SOSHIKI_CD        ,
									@C_KYUKAKYUSYA_KBN   ,
									@C_SAGYO_DATE_F      ,
									@C_SAGYO_DATE_T      ,
									@C_HATSU_AREA_CD     ,
									@C_HATSU_TODOFUKEN_CD,
									@C_CHAKU_AREA_CD     ,
									@C_CHAKU_TODOFUKEN_CD,
									@C_HATSU_SOSHIKI_CD  ,
									@C_SEIYAKU_KBN_OP    ,
									@C_KYOSO_KBN
									
		END
	END

SP_KYUKAKYUSYA_KENSAKU_MANAGER_EXIT:
	SET NOCOUNT OFF
	RETURN @ERR

END


GO

